ktor:
  application:
    modules:
      - ru.fmsh.ApplicationKt.module
  deployment:
    port: 8080
postgres:
  url: "jdbc:postgresql://localhost:5432/utair-test"
  user: postgres
  password: $DB_PASSWORD
task:
  default:
    limit: 100